[project]
authors = ["craftlife <craftlinks@protonmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-hdc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tests = "mojo test -I src test"


[dependencies]
max = "*"
redis-py = ">=6.0.0,<7"
